# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8ae9048399fd005aa7b311b3649e46e5d74a44764221def7ceaafeab265bd1e2f2897bfc67a346a1505815649ad6d958279ad600ed304181b53332fd44a2c23

test:
  secret_key_base: dc71980fa3471d28754638977743340ca1fe04dc90c8a4a8f6ab9c531c3379effe5fc5b36929e8a9fd219936e22ad385ee215709b2797db6d59e4bf2805f6846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
